// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRrtuAxX20d4QcjKRC_GeqsKpHb1UoqRg',
    appId: '1:13936767497:web:f3c2b14add27ea75ce7ed8',
    messagingSenderId: '13936767497',
    projectId: 'news-app-rewan',
    authDomain: 'news-app-rewan.firebaseapp.com',
    storageBucket: 'news-app-rewan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9LekQKbCja4_1HrUIR4RDysj2j_KnVW8',
    appId: '1:13936767497:android:d44684b81831a4d4ce7ed8',
    messagingSenderId: '13936767497',
    projectId: 'news-app-rewan',
    storageBucket: 'news-app-rewan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSzTFGyKOmC_ecTKfDH8U5S7uKyY8KniU',
    appId: '1:13936767497:ios:5c551b9ba603d4d7ce7ed8',
    messagingSenderId: '13936767497',
    projectId: 'news-app-rewan',
    storageBucket: 'news-app-rewan.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSzTFGyKOmC_ecTKfDH8U5S7uKyY8KniU',
    appId: '1:13936767497:ios:5c551b9ba603d4d7ce7ed8',
    messagingSenderId: '13936767497',
    projectId: 'news-app-rewan',
    storageBucket: 'news-app-rewan.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRrtuAxX20d4QcjKRC_GeqsKpHb1UoqRg',
    appId: '1:13936767497:web:65956e49c5f61419ce7ed8',
    messagingSenderId: '13936767497',
    projectId: 'news-app-rewan',
    authDomain: 'news-app-rewan.firebaseapp.com',
    storageBucket: 'news-app-rewan.firebasestorage.app',
  );
}
